// packages/react/src/Avatar.tsx
import { forwardRef, useState, type HTMLAttributes, type ReactNode } from 'react';

/** Props for {@link Avatar}. */
export interface AvatarProps extends HTMLAttributes<HTMLSpanElement> {
  src?: string;
  alt?: string;
  /** Shown when there is no `src` or the image fails to load. */
  fallback?: ReactNode;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  shape?: 'circle' | 'square';
}

/** Avatar primitive: `hl-avatar` with image + graceful fallback. */
export const Avatar = forwardRef<HTMLSpanElement, AvatarProps>(function Avatar(
  { src, alt = '', fallback, size, shape, className, children, ...rest },
  ref,
) {
  const [failed, setFailed] = useState(false);
  const showImage = src && !failed;

  return (
    <span
      {...rest}
      ref={ref}
      className={['hl-avatar', className].filter(Boolean).join(' ')}
      data-hl-size={size}
      data-hl-shape={shape === 'square' ? 'square' : undefined}
    >
      {showImage ? (
        <img src={src} alt={alt} onError={() => setFailed(true)} />
      ) : (
        (fallback ?? children)
      )}
    </span>
  );
});

/** Props for {@link AvatarGroup}. */
export type AvatarGroupProps = HTMLAttributes<HTMLDivElement>;

/** Overlapping stack of avatars. */
export const AvatarGroup = forwardRef<HTMLDivElement, AvatarGroupProps>(function AvatarGroup(
  { className, children, ...rest },
  ref,
) {
  return (
    <div {...rest} ref={ref} className={['hl-avatar-group', className].filter(Boolean).join(' ')}>
      {children}
    </div>
  );
});

// packages/svelte/src/components/Avatar.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLSpanElement> {
    /** Image source; on load failure the fallback `children` render instead. */
    src?: string;
    /** Alternative text for the image; empty when the name is shown alongside. */
    alt?: string;
    /** Avatar size. */
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    /** Avatar shape. Defaults to a circle. */
    shape?: 'circle' | 'square';
    /** Fallback content, typically initials. */
    children?: Snippet;
  }

  let { src, alt = '', size, shape, class: klass, children, ...rest }: Props = $props();
  let failed = $state(false);
</script>

<span
  {...rest}
  class={['hl-avatar', klass]}
  data-hl-size={size}
  data-hl-shape={shape === 'square' ? 'square' : undefined}
>
  {#if src && !failed}
    <img {src} {alt} onerror={() => (failed = true)} />
  {:else}
    {@render children?.()}
  {/if}
</span>
