// packages/react/src/Checkbox.tsx
import { forwardRef, type InputHTMLAttributes, type ReactNode } from 'react';
import { cx } from './util.js';
import { useFieldControl } from './internal/useFieldControl.js';

/** Props for {@link Checkbox}. */
export interface CheckboxProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> {
  children?: ReactNode;
}

/**
 * Checkbox built on a native `<input type="checkbox">`, label-wrapped. Inside
 * a {@link Field} it picks up `id`, `aria-describedby`, `aria-invalid`, and
 * `required`.
 */
export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(
  { children, className, ...rest },
  ref,
) {
  const props = useFieldControl(rest);
  return (
    <label className={cx('hl-checkbox', className)}>
      <input {...props} ref={ref} type="checkbox" />
      {children != null && <span>{children}</span>}
    </label>
  );
});

// packages/svelte/src/components/Checkbox.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLInputAttributes } from 'svelte/elements';
  import { useField } from '../context.js';

  interface Props extends Omit<HTMLInputAttributes, 'type' | 'checked'> {
    /** Checked state; two-way bindable (`bind:checked`). */
    checked?: boolean;
    /** Label text rendered next to the box. */
    children?: Snippet;
  }

  let {
    checked = $bindable(),
    id,
    required,
    'aria-describedby': describedBy,
    'aria-invalid': ariaInvalid,
    class: klass,
    children,
    ...rest
  }: Props = $props();
  // Optional: wires id/aria-describedby/aria-invalid/required when inside a <Field>.
  const field = useField();
</script>

<label class={['hl-checkbox', klass]}>
  <input
    {...rest}
    id={id ?? field?.id}
    required={required ?? (field?.required || undefined)}
    aria-describedby={describedBy ?? field?.describedBy}
    aria-invalid={ariaInvalid ?? (field?.invalid || undefined)}
    type="checkbox"
    bind:checked
  />
  {#if children}<span>{@render children()}</span>{/if}
</label>
