// packages/react/src/Input.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';
import { cx } from './util.js';
import { useFieldControl } from './internal/useFieldControl.js';

/** Props for {@link Input}. */
export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> {
  size?: 'sm' | 'md' | 'lg';
  /** Error state; also inherited from an enclosing {@link Field}. */
  invalid?: boolean;
}

/**
 * Text input styled with the `hl-input` primitive. Inside a {@link Field} it
 * picks up `id`, `aria-describedby`, `aria-invalid`, and `required`.
 */
export const Input = forwardRef<HTMLInputElement, InputProps>(function Input(
  { size, invalid, className, ...rest },
  ref,
) {
  const props = useFieldControl(rest, invalid);
  return (
    <input
      {...props}
      ref={ref}
      className={cx('hl-input', className)}
      data-hl-size={size}
      data-hl-invalid={props['aria-invalid'] || undefined}
    />
  );
});

// packages/svelte/src/components/Input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements';
  import { useField } from '../context.js';

  interface Props extends Omit<HTMLInputAttributes, 'size'> {
    /** Current value; two-way bindable (`bind:value`). */
    value?: string | number;
    /** Control size. */
    size?: 'sm' | 'md' | 'lg';
    /** Mark the control invalid; also inherited from an enclosing `<Field invalid>`. */
    invalid?: boolean;
  }

  let {
    value = $bindable(),
    size,
    invalid = false,
    id,
    required,
    'aria-describedby': describedBy,
    class: klass,
    ...rest
  }: Props = $props();
  // Optional: wires id/aria-describedby/aria-invalid/required when inside a <Field>.
  const field = useField();
  const isInvalid = $derived(invalid || Boolean(field?.invalid));
</script>

<input
  {...rest}
  id={id ?? field?.id}
  required={required ?? (field?.required || undefined)}
  aria-describedby={describedBy ?? field?.describedBy}
  bind:value
  class={['hl-input', klass]}
  data-hl-size={size}
  data-hl-invalid={isInvalid || undefined}
  aria-invalid={isInvalid || undefined}
/>
