// packages/react/src/Modal.tsx
import { useEffect, type HTMLAttributes } from 'react';
import { enhanceModal, type ModalApi } from '@hydrateless/enhancers';
import { useEnhancer } from './useEnhancer.js';
import { cx, useLatest } from './util.js';

/** Props for {@link Modal}. */
export interface ModalProps extends Omit<HTMLAttributes<HTMLDialogElement>, 'title'> {
  /** Controlled open state (pair with `onOpenChange`). */
  open?: boolean;
  /** Open the dialog initially for uncontrolled usage. */
  defaultOpen?: boolean;
  /** Called after the dialog opens or closes (Escape, backdrop, close buttons). */
  onOpenChange?: (open: boolean) => void;
  closeOnBackdrop?: boolean;
}

/**
 * Dialog overlay built on the native `<dialog>` element and the modal
 * enhancer, which adds a focus trap, body scroll-lock, and a background
 * `inert` barrier. Compose with `<ModalHeader>`, `<ModalBody>`, and
 * `<ModalFooter>`. Open state works uncontrolled (`defaultOpen`, or a
 * `command="show-modal"` invoker button) or controlled (`open` +
 * `onOpenChange`).
 *
 * ```tsx
 * <Modal open={open} onOpenChange={setOpen}>
 *   <ModalHeader>Confirm</ModalHeader>
 *   <ModalBody>Are you sure?</ModalBody>
 *   <ModalFooter><Button onClick={() => setOpen(false)}>Close</Button></ModalFooter>
 * </Modal>
 * ```
 */
export function Modal({
  open,
  defaultOpen,
  onOpenChange,
  closeOnBackdrop = true,
  className,
  children,
  ...rest
}: ModalProps) {
  const onOpenChangeRef = useLatest(onOpenChange);
  const initialOpenRef = useLatest(open ?? defaultOpen);

  const { ref, api } = useEnhancer<HTMLDialogElement, ModalApi>(
    (el) =>
      enhanceModal(el, {
        closeOnBackdrop,
        defaultOpen: initialOpenRef.current,
        onOpenChange: (next) => onOpenChangeRef.current?.(next),
      }),
    [closeOnBackdrop],
  );

  useEffect(() => {
    if (open != null) api.current?.setOpen(open);
  }, [open, api]);

  return (
    <dialog {...rest} ref={ref} data-hl-modal className={cx('hl-modal', className)}>
      {children}
    </dialog>
  );
}

/** Props shared by the {@link Modal} section components. */
export type ModalSectionProps = HTMLAttributes<HTMLDivElement>;

/** Modal heading region; its content labels the dialog for assistive tech. */
export function ModalHeader({ className, ...rest }: ModalSectionProps) {
  return <div {...rest} className={cx('hl-modal-header', className)} />;
}

/** Modal main content region. */
export function ModalBody({ className, ...rest }: ModalSectionProps) {
  return <div {...rest} className={cx('hl-modal-body', className)} />;
}

/** Modal actions region. */
export function ModalFooter({ className, ...rest }: ModalSectionProps) {
  return <div {...rest} className={cx('hl-modal-footer', className)} />;
}

// packages/svelte/src/components/Modal.svelte
<script lang="ts">
  import { enhanceModal } from '@hydrateless/enhancers';
  import { untrack } from 'svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLDialogAttributes } from 'svelte/elements';
  import { useEnhancer } from '../useEnhancer.svelte.js';

  interface Props extends HTMLDialogAttributes {
    /** Open state; two-way bindable (`bind:open`). */
    open?: boolean;
    /** Open the dialog initially for uncontrolled usage. */
    defaultOpen?: boolean;
    /** Called after the dialog opens or closes (including native Escape). */
    onOpenChange?: (open: boolean) => void;
    /** Let Escape and a backdrop click close the dialog. Defaults to `true`. */
    closeOnBackdrop?: boolean;
    /** Dialog content; compose with `<ModalHeader>`, `<ModalBody>`, `<ModalFooter>`. */
    children?: Snippet;
  }

  let {
    defaultOpen = false,
    open = $bindable(),
    onOpenChange,
    closeOnBackdrop = true,
    class: klass,
    children,
    ...rest
  }: Props = $props();
  // svelte-ignore state_referenced_locally -- seeds the uncontrolled initial value once
  if (open === undefined) open = defaultOpen;

  const modal = useEnhancer(enhanceModal, () => ({
    closeOnBackdrop,
    defaultOpen: untrack(() => open),
    onOpenChange: (next) => {
      open = next;
      onOpenChange?.(next);
    },
  }));

  $effect(() => {
    if (open != null) modal.api?.setOpen(open);
  });
</script>

<dialog {...rest} class={['hl-modal', klass]} data-hl-modal {@attach modal.attach}>
  {@render children?.()}
</dialog>
