// packages/react/src/SegmentedControl.tsx
import { forwardRef, type HTMLAttributes, type ReactNode } from 'react';
import { cx } from './util.js';
import { useControlled } from './internal/useControlled.js';
import { useHlId } from './internal/useHlId.js';

/** A single option in a {@link SegmentedControl}. */
export interface SegmentedOption {
  label: ReactNode;
  value: string;
  disabled?: boolean;
}

/** Props for {@link SegmentedControl}. */
export interface SegmentedControlProps extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
  options: SegmentedOption[];
  /** Controlled selected value (pair with `onValueChange`). */
  value?: string;
  /** Initially selected value for uncontrolled usage; defaults to the first option. */
  defaultValue?: string;
  /** Called with the newly selected value. */
  onValueChange?: (value: string) => void;
  /** Shared `name` for the underlying radios; generated when omitted. */
  name?: string;
  size?: 'sm' | 'md' | 'lg';
}

/**
 * Segmented control: an `hl-segmented` radiogroup built on native radios, so
 * keyboard navigation comes for free. Uncontrolled (`defaultValue`, falling
 * back to the first option) or controlled (`value` + `onValueChange`).
 */
export const SegmentedControl = forwardRef<HTMLDivElement, SegmentedControlProps>(
  function SegmentedControl(
    { options, value: valueProp, defaultValue, onValueChange, name, size, className, ...rest },
    ref,
  ) {
    const [value, setValue] = useControlled(
      valueProp,
      defaultValue ?? options[0]?.value,
      onValueChange,
    );
    const groupName = useHlId('segmented', name);

    return (
      <div
        {...rest}
        ref={ref}
        role="radiogroup"
        className={cx('hl-segmented', className)}
        data-hl-size={size}
      >
        {options.map((option) => (
          <label className="hl-segmented-item" key={option.value}>
            <input
              type="radio"
              name={groupName}
              value={option.value}
              checked={value === option.value}
              disabled={option.disabled}
              onChange={() => setValue(option.value)}
            />
            <span>{option.label}</span>
          </label>
        ))}
      </div>
    );
  },
);

// packages/svelte/src/components/SegmentedControl.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements';

  interface SegmentedOption {
    /** Visible label. */
    label: string;
    /** Value reported when the segment is selected. */
    value: string;
    /** Render the segment disabled. */
    disabled?: boolean;
  }

  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'onchange'> {
    /** Segments to render, in order. */
    options?: SegmentedOption[];
    /** Selected value; two-way bindable (`bind:value`). */
    value?: string;
    /** Initially selected value for uncontrolled usage. Defaults to the first option. */
    defaultValue?: string;
    /** Called with the new value after every selection change. */
    onValueChange?: (value: string) => void;
    /** Shared `name` of the underlying radios; generated when omitted. */
    name?: string;
    /** Control size. */
    size?: 'sm' | 'md' | 'lg';
  }

  let {
    options = [],
    value = $bindable(),
    defaultValue,
    onValueChange,
    name,
    size,
    class: klass,
    ...rest
  }: Props = $props();
  // svelte-ignore state_referenced_locally -- seeds the uncontrolled initial value once
  if (value === undefined) value = defaultValue ?? options[0]?.value;
  // SSR-safe: $props.id() is stable across server and client renders.
  const generatedId = $props.id();
  const groupName = `hl-seg-${generatedId}`;

  function select(next: string) {
    value = next;
    onValueChange?.(next);
  }
</script>

<div {...rest} role="radiogroup" class={['hl-segmented', klass]} data-hl-size={size}>
  {#each options as option (option.value)}
    <label class="hl-segmented-item">
      <input
        type="radio"
        name={name ?? groupName}
        value={option.value}
        checked={value === option.value}
        disabled={option.disabled}
        onchange={() => select(option.value)}
      />
      <span>{option.label}</span>
    </label>
  {/each}
</div>
