// packages/react/src/SkipLink.tsx
import { type AnchorHTMLAttributes, type ReactNode } from 'react';
import { cx } from './util.js';

/** Props for {@link SkipLink}. */
export type SkipLinkProps = AnchorHTMLAttributes<HTMLAnchorElement> & {
  children?: ReactNode;
};

/** Accessibility skip-navigation link, visually hidden until focused. */
export function SkipLink({ children = 'Skip to content', className, ...rest }: SkipLinkProps) {
  return (
    <a {...rest} className={cx('hl-skip-link', className)}>
      {children}
    </a>
  );
}

// packages/svelte/src/components/SkipLink.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAnchorAttributes } from 'svelte/elements';

  interface Props extends HTMLAnchorAttributes {
    children?: Snippet;
  }

  let { class: klass, children, ...rest }: Props = $props();
</script>

<a {...rest} class={['hl-skip-link', klass]}>
  {#if children}{@render children()}{:else}Skip to content{/if}
</a>
