// packages/react/src/Slider.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';
import { cx } from './util.js';
import { useFieldControl } from './internal/useFieldControl.js';

/** Props for {@link Slider}. */
export type SliderProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'type'>;

/**
 * Range slider primitive: `<input type="range" class="hl-slider">`. Inside a
 * {@link Field} it picks up `id`, `aria-describedby`, `aria-invalid`, and
 * `required`.
 */
export const Slider = forwardRef<HTMLInputElement, SliderProps>(function Slider(
  { className, ...rest },
  ref,
) {
  const props = useFieldControl(rest);
  return <input {...props} ref={ref} type="range" className={cx('hl-slider', className)} />;
});

// packages/svelte/src/components/Slider.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements';
  import { useField } from '../context.js';

  interface Props extends Omit<HTMLInputAttributes, 'type'> {
    /** Current value; two-way bindable (`bind:value`). */
    value?: string | number;
  }

  let {
    value = $bindable(),
    id,
    required,
    'aria-describedby': describedBy,
    'aria-invalid': ariaInvalid,
    class: klass,
    ...rest
  }: Props = $props();
  // Optional: wires id/aria-describedby/aria-invalid/required when inside a <Field>.
  const field = useField();
</script>

<input
  {...rest}
  id={id ?? field?.id}
  required={required ?? (field?.required || undefined)}
  aria-describedby={describedBy ?? field?.describedBy}
  aria-invalid={ariaInvalid ?? (field?.invalid || undefined)}
  type="range"
  class={['hl-slider', klass]}
  bind:value
/>
