// packages/react/src/Table.tsx
import { forwardRef, type TableHTMLAttributes } from 'react';
import { cx } from './util.js';

/** Props for {@link Table}. */
export interface TableProps extends Omit<TableHTMLAttributes<HTMLTableElement>, 'align'> {
  /** Zebra-stripe the body rows. */
  striped?: boolean;
  /** Highlight body rows on hover. */
  hover?: boolean;
  /** Default cell alignment. */
  align?: 'start' | 'center' | 'end';
  /** Cell density. */
  size?: 'sm' | 'md' | 'lg';
}

/**
 * Semantic table styled with the `hl-table` primitive. Pass `<thead>`,
 * `<tbody>`, and friends as children; wrap it in an element with
 * `overflow-x: auto` (the `hl-table-wrapper` class) when rows may overflow.
 */
export const Table = forwardRef<HTMLTableElement, TableProps>(function Table(
  { striped, hover, align, size, className, children, ...rest },
  ref,
) {
  return (
    <table
      {...rest}
      ref={ref}
      className={cx('hl-table', className)}
      data-hl-striped={striped || undefined}
      data-hl-hover={hover || undefined}
      data-hl-align={align}
      data-hl-size={size}
    >
      {children}
    </table>
  );
});

// packages/svelte/src/components/Table.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLTableAttributes } from 'svelte/elements';

  interface Props extends Omit<HTMLTableAttributes, 'align'> {
    /** Zebra-stripe the body rows. */
    striped?: boolean;
    /** Highlight a body row under the pointer. */
    hover?: boolean;
    /** Default text alignment of cells (logical, RTL-aware). */
    align?: 'start' | 'center' | 'end';
    /** Cell padding scale. */
    size?: 'sm' | 'md' | 'lg';
    /** `<thead>`, `<tbody>`, `<tfoot>`, and `<caption>` as usual. */
    children?: Snippet;
  }

  let { striped, hover, align, size, class: klass, children, ...rest }: Props = $props();
</script>

<table
  {...rest}
  class={['hl-table', klass]}
  data-hl-striped={striped || undefined}
  data-hl-hover={hover || undefined}
  data-hl-align={align}
  data-hl-size={size}
>
  {@render children?.()}
</table>
