// packages/react/src/Tabs.tsx
import { useEffect, type ButtonHTMLAttributes, type HTMLAttributes } from 'react';
import { enhanceTabs, type EnhanceTabsOptions, type TabsApi } from '@hydrateless/enhancers';
import { useEnhancer } from './useEnhancer.js';
import { useLatest } from './util.js';

/** Props for {@link Tabs}. */
export interface TabsProps extends HTMLAttributes<HTMLDivElement> {
  /** `manual` (default): arrows move focus, Enter/Space activates. `automatic`: arrows activate immediately. */
  activation?: EnhanceTabsOptions['activation'];
  orientation?: EnhanceTabsOptions['orientation'];
  /** Controlled value of the selected tab (pair with `onValueChange`). */
  value?: string;
  /** Initial value for uncontrolled usage. */
  defaultValue?: string;
  /** Called with the new tab value after every selection change. */
  onValueChange?: (value: string) => void;
}

/**
 * Tabbed interface root. Compose with `<TabList>`, `<Tab>`, and `<TabPanel>`.
 * The enhancer wires ARIA roles, roving tabindex, and arrow-key navigation
 * once the markup is mounted. Tab values come from each `<Tab value>`,
 * defaulting to the index; selection works uncontrolled (`defaultValue`) or
 * controlled (`value` + `onValueChange`).
 *
 * ```tsx
 * <Tabs value={tab} onValueChange={setTab}>
 *   <TabList>
 *     <Tab value="overview">Overview</Tab>
 *     <Tab value="install">Install</Tab>
 *   </TabList>
 *   <TabPanel>Zero runtime by default.</TabPanel>
 *   <TabPanel>npm install hydrateless</TabPanel>
 * </Tabs>
 * ```
 */
export function Tabs({
  activation,
  orientation,
  value,
  defaultValue,
  onValueChange,
  children,
  ...rest
}: TabsProps) {
  const onValueChangeRef = useLatest(onValueChange);
  const initialValueRef = useLatest(value ?? defaultValue);

  const { ref, api } = useEnhancer<HTMLDivElement, TabsApi>(
    (el) =>
      enhanceTabs(el, {
        activation,
        orientation,
        defaultValue: initialValueRef.current,
        onValueChange: (next) => onValueChangeRef.current?.(next),
      }),
    [activation, orientation],
  );

  useEffect(() => {
    if (value != null) api.current?.setValue(value);
  }, [value, api]);

  return (
    <div {...rest} data-hl-tabs ref={ref}>
      {children}
    </div>
  );
}

/** Props for {@link TabList}. */
export type TabListProps = HTMLAttributes<HTMLDivElement>;

/** The row of tab triggers. Renders `role="tablist"`. */
export function TabList({ children, ...rest }: TabListProps) {
  return (
    <div {...rest} role="tablist">
      {children}
    </div>
  );
}

/** Props for {@link Tab}. */
export interface TabProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Stable value identifying this tab; defaults to its index. */
  value?: string;
}

/** A single tab trigger. Renders `role="tab"`. */
export function Tab({ children, type, value, ...rest }: TabProps) {
  return (
    <button {...rest} type={type ?? 'button'} role="tab" data-hl-value={value}>
      {children}
    </button>
  );
}

/** Props for {@link TabPanel}. */
export type TabPanelProps = HTMLAttributes<HTMLDivElement>;

/** Content for the matching tab. Renders `role="tabpanel"`. */
export function TabPanel({ children, ...rest }: TabPanelProps) {
  return (
    <div {...rest} role="tabpanel">
      {children}
    </div>
  );
}

// packages/svelte/src/components/Tabs.svelte
<script lang="ts">
  import { enhanceTabs, type EnhanceTabsOptions } from '@hydrateless/enhancers';
  import { untrack } from 'svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { setTabsContext } from '../context.js';
  import { useEnhancer } from '../useEnhancer.svelte.js';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    /** `manual` (default): arrows move focus, Enter/Space selects. `automatic`: arrows select. */
    activation?: EnhanceTabsOptions['activation'];
    /** Layout of the tab list; also picks the arrow keys used. */
    orientation?: EnhanceTabsOptions['orientation'];
    /** Selected tab value; two-way bindable (`bind:value`). */
    value?: string;
    /** Initially selected tab for uncontrolled usage. Defaults to the first tab. */
    defaultValue?: string;
    /** Called with the new tab value after every selection change. */
    onValueChange?: (value: string) => void;
    /** A `<TabList>` followed by one `<TabPanel>` per tab. */
    children?: Snippet;
  }

  let {
    activation,
    orientation,
    value = $bindable(),
    defaultValue,
    onValueChange,
    children,
    ...rest
  }: Props = $props();
  // svelte-ignore state_referenced_locally -- seeds the uncontrolled initial value once
  if (value === undefined) value = defaultValue;

  // Tabs and panels register in document order so `aria-selected`/`hidden`
  // render on the server and the enhancer finds them already in agreement.
  const tabValues: string[] = [];
  let panelCount = 0;
  setTabsContext({
    get value() {
      return value ?? tabValues[0];
    },
    registerTab(tabValue) {
      const index = tabValues.length;
      tabValues.push(tabValue ?? String(index));
      return index;
    },
    registerPanel() {
      return panelCount++;
    },
    tabValueAt: (index) => tabValues[index],
  });

  const tabs = useEnhancer(enhanceTabs, () => ({
    activation,
    orientation,
    defaultValue: untrack(() => value),
    onValueChange: (next) => {
      value = next;
      onValueChange?.(next);
    },
  }));

  $effect(() => {
    if (value != null) tabs.api?.setValue(value);
  });
</script>

<div {...rest} data-hl-tabs data-hl-orientation={orientation} {@attach tabs.attach}>
  {@render children?.()}
</div>
