// packages/react/src/Tooltip.tsx
import {
  cloneElement,
  isValidElement,
  useEffect,
  useId,
  useRef,
  type ReactElement,
  type ReactNode,
} from 'react';
import { enhanceTooltip } from '@hydrateless/enhancers';

/** Props for {@link Tooltip}. */
export interface TooltipProps {
  /** The hint text shown on hover/focus. */
  label: ReactNode;
  /** A single focusable element that triggers the tooltip. */
  children: ReactElement;
  id?: string;
}

/**
 * Adds an accessible tooltip to a focusable trigger. The enhancer toggles the
 * tip on hover/focus and dismisses it on Escape.
 */
export function Tooltip({ label, children, id }: TooltipProps) {
  const generatedId = useId().replace(/:/g, '');
  const tipId = id ?? `hl-tip-${generatedId}`;
  const ref = useRef<HTMLSpanElement>(null);

  useEffect(() => {
    if (!ref.current) return;
    return enhanceTooltip(ref.current).destroy;
  }, [tipId]);

  const trigger = isValidElement(children)
    ? cloneElement(children as ReactElement<Record<string, unknown>>, {
        'data-hl-tooltip': tipId,
        'aria-describedby': tipId,
      })
    : children;

  return (
    <span ref={ref} style={{ position: 'relative', display: 'inline-block' }}>
      {trigger}
      <span id={tipId} role="tooltip" hidden>
        {label}
      </span>
    </span>
  );
}

// packages/svelte/src/components/Tooltip.svelte
<script lang="ts">
  import { enhanceTooltip } from '@hydrateless/enhancers';
  import type { Snippet } from 'svelte';

  interface Props {
    /** The hint text shown on hover/focus. */
    label?: string;
    /** Richer hint content; overrides `label` when provided. */
    tip?: Snippet;
    id?: string;
    /** A single focusable element that triggers the tooltip. */
    children?: Snippet;
  }

  let { label, tip, id, children }: Props = $props();
  const generatedId = `hl-tip-${Math.random().toString(36).slice(2, 8)}`;
  const tipId = $derived(id ?? generatedId);
  let host = $state<HTMLSpanElement>();

  $effect(() => {
    if (!host) return;
    const trigger = host.querySelector<HTMLElement>(':scope > :first-child');
    if (trigger) {
      trigger.setAttribute('data-hl-tooltip', tipId);
      trigger.setAttribute('aria-describedby', tipId);
    }
    return enhanceTooltip(host).destroy;
  });
</script>

<span bind:this={host} style="position:relative;display:inline-block">
  {@render children?.()}
  <span id={tipId} role="tooltip" hidden
    >{#if tip}{@render tip()}{:else}{label}{/if}</span
  >
</span>
