// packages/svelte/src/components/Alert.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Intent = 'neutral' | 'primary' | 'danger' | 'success' | 'warning' | 'info';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    intent?: Intent;
    title?: string;
    icon?: Snippet;
    children?: Snippet;
  }

  let { intent, title, icon, role = 'alert', class: klass, children, ...rest }: Props = $props();
</script>

<div {...rest} {role} class={['hl-alert', klass]} data-hl-intent={intent}>
  {@render icon?.()}
  <div class="hl-alert-body">
    {#if title != null}<p class="hl-alert-title">{title}</p>{/if}
    {@render children?.()}
  </div>
</div>

// packages/react/src/Alert.tsx
import { forwardRef, type HTMLAttributes, type ReactNode } from 'react';

/** Props for {@link Alert}. */
export interface AlertProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  intent?: 'info' | 'success' | 'warning' | 'danger' | 'neutral';
  title?: ReactNode;
  /** Leading icon, rendered before the body. */
  icon?: ReactNode;
}

/** Alert primitive: `hl-alert` with intent, optional icon + title. */
export const Alert = forwardRef<HTMLDivElement, AlertProps>(function Alert(
  { intent, title, icon, className, children, ...rest },
  ref,
) {
  return (
    <div
      {...rest}
      ref={ref}
      role={rest.role ?? 'alert'}
      className={['hl-alert', className].filter(Boolean).join(' ')}
      data-hl-intent={intent}
    >
      {icon}
      <div className="hl-alert-body">
        {title != null && <p className="hl-alert-title">{title}</p>}
        {children}
      </div>
    </div>
  );
});
