// packages/svelte/src/components/Badge.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLSpanElement> {
    intent?: 'neutral' | 'primary' | 'danger' | 'success' | 'warning' | 'info';
    variant?: 'soft' | 'solid' | 'outline';
    size?: 'sm' | 'md';
    children?: Snippet;
  }

  let { intent, variant, size, class: klass, children, ...rest }: Props = $props();
</script>

<span
  {...rest}
  class={['hl-badge', klass]}
  data-hl-intent={intent}
  data-hl-variant={variant}
  data-hl-size={size}
>
  {@render children?.()}
</span>

// packages/react/src/Badge.tsx
import { forwardRef, type HTMLAttributes } from 'react';

/** Props for {@link Badge}. */
export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  intent?: 'neutral' | 'primary' | 'danger' | 'success' | 'warning' | 'info';
  variant?: 'soft' | 'solid' | 'outline';
  size?: 'sm' | 'md';
}

/** Badge primitive: `hl-badge` with intent/variant/size modifiers. */
export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(function Badge(
  { intent, variant, size, className, children, ...rest },
  ref,
) {
  return (
    <span
      {...rest}
      ref={ref}
      className={['hl-badge', className].filter(Boolean).join(' ')}
      data-hl-intent={intent}
      data-hl-variant={variant}
      data-hl-size={size}
    >
      {children}
    </span>
  );
});
