// packages/svelte/src/components/Disclosure.svelte
<script lang="ts">
  import { enhanceDisclosure, type DisclosureApi } from '@hydrateless/enhancers';
  import { untrack } from 'svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends Omit<HTMLAttributes<HTMLDetailsElement>, 'title'> {
    /** The clickable summary/trigger row. */
    summary?: Snippet;
    /** Open state; two-way bindable (`bind:open`). */
    open?: boolean;
    /** Open the disclosure initially for uncontrolled usage. */
    defaultOpen?: boolean;
    /**
     * Group name. Disclosures sharing a `name` are exclusive: the browser
     * closes the others when one opens, with no JavaScript.
     */
    name?: string;
    children?: Snippet;
  }

  let {
    summary,
    defaultOpen = false,
    open = $bindable(),
    name,
    class: klass,
    children,
    ...rest
  }: Props = $props();
  // svelte-ignore state_referenced_locally -- seeds the uncontrolled initial value once
  if (open === undefined) open = defaultOpen;
  let el = $state<HTMLDetailsElement>();
  let api = $state<DisclosureApi | null>(null);

  $effect(() => {
    if (!el) return;
    const handle = enhanceDisclosure(el, {
      defaultOpen: untrack(() => open),
      onOpenChange: (next) => (open = next),
    });
    api = handle.api;
    return () => {
      handle.destroy();
      api = null;
    };
  });

  $effect(() => {
    if (open != null) api?.setOpen(open);
  });
</script>

<details {...rest} bind:this={el} {name} class={['hl-disclosure', klass]} data-hl-disclosure>
  <summary>{@render summary?.()}</summary>
  <div class="hl-disclosure-panel">{@render children?.()}</div>
</details>

// packages/react/src/Disclosure.tsx
import { useEffect, type HTMLAttributes, type ReactNode } from 'react';
import { enhanceDisclosure, type DisclosureApi } from '@hydrateless/enhancers';
import { useEnhancer } from './useEnhancer.js';
import { cx, useLatest } from './util.js';

/** Props for {@link Disclosure}. */
export interface DisclosureProps extends Omit<HTMLAttributes<HTMLDetailsElement>, 'title'> {
  summary: ReactNode;
  /** Controlled open state (pair with `onOpenChange`). */
  open?: boolean;
  /** Open the disclosure initially for uncontrolled usage. */
  defaultOpen?: boolean;
  /** Called after the disclosure opens or closes. */
  onOpenChange?: (open: boolean) => void;
  /**
   * Group name. Disclosures sharing a `name` are exclusive: the browser closes
   * the others when one opens, with no JavaScript.
   */
  name?: string;
}

/**
 * A single expandable section built on native `<details>`, which handles
 * open/close (and exclusive groups, via the `name` attribute) on its own.
 * Open state works uncontrolled (`defaultOpen`) or controlled (`open` +
 * `onOpenChange`).
 */
export function Disclosure({
  summary,
  open,
  defaultOpen,
  onOpenChange,
  name,
  className,
  children,
  ...rest
}: DisclosureProps) {
  const onOpenChangeRef = useLatest(onOpenChange);
  const initialOpenRef = useLatest(open ?? defaultOpen);

  const { ref, api } = useEnhancer<HTMLDetailsElement, DisclosureApi>(
    (el) =>
      enhanceDisclosure(el, {
        defaultOpen: initialOpenRef.current,
        onOpenChange: (next) => onOpenChangeRef.current?.(next),
      }),
    [],
  );

  useEffect(() => {
    if (open != null) api.current?.setOpen(open);
  }, [open, api]);

  return (
    <details
      {...rest}
      name={name}
      className={cx('hl-disclosure', className)}
      data-hl-disclosure
      ref={ref}
    >
      <summary>{summary}</summary>
      <div className="hl-disclosure-panel">{children}</div>
    </details>
  );
}
