// packages/svelte/src/components/Kbd.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLElement> {
    /** Key name or shortcut text. */
    children?: Snippet;
  }

  let { class: klass, children, ...rest }: Props = $props();
</script>

<kbd {...rest} class={['hl-kbd', klass]}>
  {@render children?.()}
</kbd>

// packages/react/src/Kbd.tsx
import { forwardRef, type HTMLAttributes } from 'react';

/** Props for {@link Kbd}. */
export type KbdProps = HTMLAttributes<HTMLElement>;

/** Keyboard key primitive — `<kbd class="hl-kbd">`. */
export const Kbd = forwardRef<HTMLElement, KbdProps>(function Kbd(
  { className, children, ...rest },
  ref,
) {
  return (
    <kbd {...rest} ref={ref} className={['hl-kbd', className].filter(Boolean).join(' ')}>
      {children}
    </kbd>
  );
});
