// packages/svelte/src/components/Popover.svelte
<script lang="ts">
  import { enhancePopover, type EnhancePopoverOptions } from '@hydrateless/enhancers';
  import { untrack } from 'svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { useEnhancer } from '../useEnhancer.svelte.js';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    /**
     * Open state; two-way bindable (`bind:open`). The browser's light-dismiss
     * (Escape/outside click) closes it and updates the binding.
     */
    open?: boolean;
    /** Show the popover initially for uncontrolled usage. */
    defaultOpen?: boolean;
    /** Called after the popover shows or hides. */
    onOpenChange?: (open: boolean) => void;
    /** Preferred placement relative to the invoker. Defaults to `bottom`. */
    placement?: EnhancePopoverOptions['placement'];
    /** Open on hover/focus of the invoker instead of on click. */
    hover?: boolean;
    /** Popover content. Point a `<button popovertarget={id}>` at this element's `id`. */
    children?: Snippet;
  }

  let {
    defaultOpen = false,
    open = $bindable(),
    onOpenChange,
    placement,
    hover = false,
    id,
    children,
    ...rest
  }: Props = $props();
  // svelte-ignore state_referenced_locally -- seeds the uncontrolled initial value once
  if (open === undefined) open = defaultOpen;
  // An id is required so invokers can target the popover before hydration.
  const generatedId = $props.id();
  const popoverId = $derived(id ?? `hl-popover-${generatedId}`);

  const popover = useEnhancer(enhancePopover, () => ({
    placement,
    triggerEvent: hover ? ('hover' as const) : ('click' as const),
    defaultOpen: untrack(() => open),
    onOpenChange: (next) => {
      open = next;
      onOpenChange?.(next);
    },
  }));

  $effect(() => {
    if (open != null) popover.api?.setOpen(open);
  });
</script>

<div {...rest} id={popoverId} data-hl-popover popover="auto" role="dialog" {@attach popover.attach}>
  {@render children?.()}
</div>

// packages/react/src/Popover.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import {
  enhancePopover,
  type EnhancePopoverOptions,
  type PopoverApi,
} from '@hydrateless/enhancers';
import { useEnhancer } from './useEnhancer.js';
import { useControlled } from './internal/useControlled.js';
import { useSyncApi } from './internal/useSyncApi.js';
import { useForwardedRef } from './internal/useForwardedRef.js';

/** Props for {@link Popover}. */
export interface PopoverProps extends HTMLAttributes<HTMLDivElement> {
  /** Controlled open state (pair with `onOpenChange`). */
  open?: boolean;
  /** Show the popover initially for uncontrolled usage. */
  defaultOpen?: boolean;
  /** Called after the popover shows or hides (including the browser's light-dismiss). */
  onOpenChange?: (open: boolean) => void;
  /** Placement used by the JS positioning fallback. Defaults to `bottom`. */
  placement?: EnhancePopoverOptions['placement'];
  /** Open on pointer hover and focus instead of click. */
  hover?: boolean;
}

/**
 * Floating content built on the native Popover API. The surface lives in the
 * top layer with light-dismiss and Escape handled by the browser; visibility
 * works uncontrolled (`defaultOpen`, or a `popovertarget` trigger button) or
 * controlled (`open` + `onOpenChange`). Position it with the
 * `hydrateless/popover.css` styles.
 */
export const Popover = forwardRef<HTMLDivElement, PopoverProps>(function Popover(
  { open: openProp, defaultOpen, onOpenChange, placement, hover, children, ...rest },
  forwardedRef,
) {
  const ref = useForwardedRef(forwardedRef);
  const [open, setOpen] = useControlled(openProp, defaultOpen ?? false, onOpenChange);
  const api = useEnhancer<EnhancePopoverOptions, PopoverApi>(
    ref,
    enhancePopover,
    {
      placement,
      triggerEvent: hover ? 'hover' : 'click',
      defaultOpen: open,
      onOpenChange: setOpen,
    },
    [placement, hover],
  );
  useSyncApi(api, openProp, (api, open) => api.setOpen(open));

  return (
    <div {...rest} ref={ref} data-hl-popover popover="auto" role="dialog">
      {children}
    </div>
  );
});
