// packages/svelte/src/components/Separator.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLHRElement> {
    /** Direction of the rule. Defaults to `horizontal`. */
    orientation?: 'horizontal' | 'vertical';
    /** Purely visual: removes the separator from the accessibility tree. */
    decorative?: boolean;
  }

  let { orientation = 'horizontal', decorative = false, class: klass, ...rest }: Props = $props();
</script>

<hr
  {...rest}
  class={['hl-separator', klass]}
  data-hl-orientation={orientation === 'vertical' ? 'vertical' : undefined}
  aria-orientation={orientation}
  role={decorative ? 'presentation' : undefined}
/>

// packages/react/src/Separator.tsx
import { forwardRef, type HTMLAttributes } from 'react';

/** Props for {@link Separator}. */
export interface SeparatorProps extends HTMLAttributes<HTMLHRElement> {
  orientation?: 'horizontal' | 'vertical';
  /** Purely decorative — removes it from the accessibility tree. */
  decorative?: boolean;
}

/** Separator primitive — `<hr class="hl-separator">`. */
export const Separator = forwardRef<HTMLHRElement, SeparatorProps>(function Separator(
  { orientation = 'horizontal', decorative, className, ...rest },
  ref,
) {
  return (
    <hr
      {...rest}
      ref={ref}
      className={['hl-separator', className].filter(Boolean).join(' ')}
      data-hl-orientation={orientation === 'vertical' ? 'vertical' : undefined}
      aria-orientation={orientation}
      role={decorative ? 'presentation' : 'separator'}
    />
  );
});
