// packages/svelte/src/components/Skeleton.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLSpanElement> {
    variant?: 'rect' | 'text' | 'circle';
    width?: string | number;
    height?: string | number;
  }

  let { variant, width, height, style, class: klass, ...rest }: Props = $props();

  function dim(v: string | number): string {
    return typeof v === 'number' ? `${v}px` : v;
  }

  const sizeStyle = $derived(
    [
      width != null ? `inline-size:${dim(width)}` : '',
      height != null ? `block-size:${dim(height)}` : '',
      style ?? '',
    ]
      .filter(Boolean)
      .join(';'),
  );
</script>

<span
  {...rest}
  class={['hl-skeleton', klass]}
  data-hl-variant={variant}
  style={sizeStyle || undefined}
  aria-hidden="true"
></span>

// packages/react/src/Skeleton.tsx
import { forwardRef, type CSSProperties, type HTMLAttributes } from 'react';

/** Props for {@link Skeleton}. */
export interface SkeletonProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: 'rect' | 'text' | 'circle';
  width?: string | number;
  height?: string | number;
}

/** Skeleton placeholder primitive: `hl-skeleton`. */
export const Skeleton = forwardRef<HTMLSpanElement, SkeletonProps>(function Skeleton(
  { variant, width, height, className, style, ...rest },
  ref,
) {
  const sizeStyle: CSSProperties = {
    ...(width != null && { inlineSize: width }),
    ...(height != null && { blockSize: height }),
    ...style,
  };
  return (
    <span
      {...rest}
      ref={ref}
      className={['hl-skeleton', className].filter(Boolean).join(' ')}
      data-hl-variant={variant}
      style={sizeStyle}
      aria-hidden="true"
    />
  );
});
