// packages/svelte/src/components/Switch.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLInputAttributes } from 'svelte/elements';

  interface Props extends Omit<HTMLInputAttributes, 'type' | 'checked' | 'role'> {
    checked?: boolean;
    children?: Snippet;
  }

  let { checked = $bindable(), class: klass, children, ...rest }: Props = $props();
</script>

<label data-hl-switch class={klass}>
  <input {...rest} type="checkbox" role="switch" bind:checked />
  {@render children?.()}
</label>

// packages/react/src/Switch.tsx
import { type InputHTMLAttributes, type ReactNode } from 'react';

/** Props for {@link Switch}. */
export interface SwitchProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> {
  children?: ReactNode;
}

/** Toggle switch built on a native checkbox. CSS-only. */
export function Switch({ children, className, ...rest }: SwitchProps) {
  return (
    <label data-hl-switch className={className}>
      <input type="checkbox" role="switch" {...rest} />
      {children}
    </label>
  );
}
